name: Continues Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE:      Release
  BUILD_GENERATOR: MinGW Makefiles
  BUILD_DIR:       build
  
jobs:
  apsp:
    name: All-Pairs Shortest Paths
      
    runs-on: windows-2022
    
    env:
      PROJT_DIR: ${{github.workspace}}/src/apsp
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Setup MSYS (INSTALL)
      uses: msys2/setup-msys2@v2
      id: msys2
      with:
        update: true
        install: mingw-w64-x86_64-gcc
    - name: Setup MSYS (PATH)
      env:
        MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
      run: echo "$env:MSYS2_LOCATION" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Configure
      working-directory: ${{env.PROJT_DIR}}
      run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "${{env.BUILD_GENERATOR}}"
      
    - name: Build
      working-directory: ${{env.PROJT_DIR}}
      run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}
      
    - name: Test
      working-directory: ${{env.PROJT_DIR}}
      run: ctest --test-dir ${{env.BUILD_DIR}} -C ${{env.BUILD_TYPE}}
  tools:
    name: Tools
      
    runs-on: windows-2022
    
    env:
      PROJT_DIR: ${{github.workspace}}/src/tools
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Setup MSYS (INSTALL)
      uses: msys2/setup-msys2@v2
      id: msys2
      with:
        update: true
        install: mingw-w64-x86_64-gcc
    - name: Setup MSYS (PATH)
      env:
        MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
      run: echo "$env:MSYS2_LOCATION" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Configure
      working-directory: ${{env.PROJT_DIR}}
      run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "${{env.BUILD_GENERATOR}}"

    - name: Build
      working-directory: ${{env.PROJT_DIR}}
      run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{env.PROJT_DIR}}
      run: ctest --test-dir ${{env.BUILD_DIR}} -C ${{env.BUILD_TYPE}}
