name: Continues Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: All-Pairs Shortest Paths
    env:
      WORK_DIR:        ${{github.workspace}}/src/apsp

      BUILD_TYPE:      Release
      BUILD_GENERATOR: MinGW Makefiles
      BUILD_DIR:       ${{env.WORK_DIR}}/src/apsp/build
      
    runs-on: windows-latest

    steps:
    - name: Setup MINGW (ENVIRONMENT & COMPILER)
      uses: msys2/setup-msys2@v2
      with:
        update:  true
        install: mingw-w64-x86_64-gcc
        
    - name: Setup MINGW (SYSTEM PATH)
      run:  echo "D:/a/_temp/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      run: cmake -S ${{env.WORK_DIR}} -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "${{env.BUILD_GENERATOR}}"

    - name: Build
      run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest --test-dir ${{env.BUILD_DIR}} -C ${{env.BUILD_TYPE}}
