name: All-pairs Shortests Paths

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  GENERATOR:  MinGW Makefiles

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-x86_64-gcc
        
    - name: Put MSYS2_MinGW64 on PATH
      run: echo "D:/a/_temp/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      working-directory: ${{github.workspace}}/src/apsp
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "${{env.GENERATOR}}"

    - name: Build
      working-directory: ${{github.workspace}}/src/apsp
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/src/apsp/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
