name: Continues Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE:      Release
  BUILD_GENERATOR: MinGW Makefiles
  BUILD_DIR:       build
  
jobs:
  changes:
    name: Detect Changes
    
    runs-on: ubuntu-latest
    
    outputs:
      apsp: ${{ steps.filter.outputs.apsp }}
      common: ${{ steps.filter.outputs.common }}
      tools: ${{ steps.filter.outputs.tools }}
    
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          apsp:
            - 'src/apsp/**'
          common:
            - 'src/common/**'
          tools:
            - 'src/tools/**'
            
  apsp:
    name: All-Pairs Shortest Paths
      
    runs-on: windows-2022
    needs: changes
    if: ${{ needs.changes.outputs.apsp == 'true' || needs.changes.outputs.common == 'true' }}
    
    env:
      PROJT_DIR: ${{github.workspace}}/src/apsp
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Setup
      uses: msys2/setup-msys2@v2

    - name: Configure
      working-directory: ${{env.PROJT_DIR}}
      run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "${{env.BUILD_GENERATOR}}"
      
    - name: Build
      working-directory: ${{env.PROJT_DIR}}
      run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}
      
    - name: Test
      working-directory: ${{env.PROJT_DIR}}
      run: ctest --test-dir ${{env.BUILD_DIR}} -C ${{env.BUILD_TYPE}}
  tools:
    name: Tools
      
    runs-on: windows-2022
    needs: changes
    if: ${{ needs.changes.outputs.tools == 'true' || needs.changes.outputs.common == 'true' }}
    
    env:
      PROJT_DIR: ${{github.workspace}}/src/tools
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
        
    - name: Setup
      uses: msys2/setup-msys2@v2

    - name: Configure
      working-directory: ${{env.PROJT_DIR}}
      run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "${{env.BUILD_GENERATOR}}"

    - name: Build
      working-directory: ${{env.PROJT_DIR}}
      run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{env.PROJT_DIR}}
      run: ctest --test-dir ${{env.BUILD_DIR}} -C ${{env.BUILD_TYPE}}
